import { jsPDF } from 'jspdf';

/**
 * Export a debate to PDF format
 * @param {Object} debate - The debate object with transcript and verdict
 */
export const exportDebateToPDF = (debate) => {
  const doc = new jsPDF();
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Helper function to add text with word wrap
  const addText = (text, fontSize = 11, isBold = false, color = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(...color);
    
    const lines = doc.splitTextToSize(text, maxWidth);
    
    // Check if we need a new page
    if (yPosition + (lines.length * fontSize * 0.5) > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
    
    doc.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  // Helper function to add a section divider
  const addDivider = () => {
    if (yPosition + 10 > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
    }
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;
  };

  // Title
  addText('MirrorMind AI - Ethical Debate', 20, true, [0, 100, 200]);
  yPosition += 5;

  // Debate Title
  const dilemma = debate.transcript?.dilemma || {};
  addText(dilemma.title || 'Untitled Debate', 16, true);
  yPosition += 5;

  // Date
  addText(`Date: ${debate.date || new Date().toLocaleDateString()}`, 10, false, [100, 100, 100]);
  yPosition += 10;

  addDivider();

  // Dilemma Section
  addText('DILEMMA', 14, true, [0, 100, 200]);
  yPosition += 5;

  addText('Option A:', 12, true);
  addText(dilemma.A || 'N/A', 11);
  yPosition += 5;

  addText('Option B:', 12, true);
  addText(dilemma.B || 'N/A', 11);
  yPosition += 5;

  addText('Context:', 12, true);
  addText(dilemma.constraints || 'N/A', 11);
  yPosition += 10;

  addDivider();

  // Debate Transcript
  addText('DEBATE TRANSCRIPT', 14, true, [0, 100, 200]);
  yPosition += 5;

  const turns = debate.transcript?.turns || [];
  turns.forEach((turn, index) => {
    // Agent name and stance
    const agentHeader = `${turn.agent} (Position: ${turn.stance || '?'})`;
    addText(agentHeader, 12, true, [50, 50, 150]);
    
    // Argument
    addText(turn.argument || 'No argument provided', 11);
    yPosition += 5;
  });

  addDivider();

  // Verdict Section
  addText('VERDICT', 14, true, [0, 100, 200]);
  yPosition += 5;

  const verdict = debate.verdict || {};
  
  addText(`Winner: Option ${verdict.final_recommendation || 'N/A'}`, 12, true, [0, 150, 0]);
  addText(`Confidence: ${verdict.confidence || 0}%`, 11);
  yPosition += 5;

  addText('Reasoning:', 12, true);
  addText(verdict.verdict || 'No verdict available', 11);
  yPosition += 10;

  // Scores
  if (verdict.scores) {
    addText('ETHICAL DIMENSION SCORES', 12, true, [0, 100, 200]);
    yPosition += 5;

    const scores = verdict.scores;
    
    // Option A scores
    addText('Option A:', 11, true);
    const optionAScores = scores.option_a || {};
    Object.entries(optionAScores).forEach(([dimension, score]) => {
      const dimLabel = dimension.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      addText(`  • ${dimLabel}: ${score}/2`, 10);
    });
    yPosition += 3;

    // Option B scores
    addText('Option B:', 11, true);
    const optionBScores = scores.option_b || {};
    Object.entries(optionBScores).forEach(([dimension, score]) => {
      const dimLabel = dimension.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      addText(`  • ${dimLabel}: ${score}/2`, 10);
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const footerText = 'Generated by MirrorMind AI - https://mirror-mind-ai.vercel.app';
  doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save the PDF
  const fileName = `debate_${debate.id || Date.now()}.pdf`;
  doc.save(fileName);
};
